import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useAuth } from "../../context/AuthContext";
import {useEffect, useState} from "react"


export default function Logout() {

    const { auth, user, logout } = useAuth();

    useEffect(() => {
        logout();
    })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" costent="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>
    </div>
  )
}
