import { Button, Row, Col, Container, Card } from "react-bootstrap";
import Head from "next/head";
import Image from "next/image";
import styles from "../../../../../styles/QuarterTaxes.module.css";
import NextNavbar from "../../../../../components/Navbar";

import { useAuth } from "../../../../../context/AuthContext";

import { useEffect, useState } from "react";

import axios from "axios"
import Link from "next/link";


const domain = process.env.NEXT_PUBLIC_API_DOMAIN_NAME


export default function QuarterTaxes({ year, truck_id }) {

    const { auth, user, token, drivers, trucks, editTruck, deleteTruck } = useAuth();

    const [quarters, setQuarters] = useState(null);


    useEffect(() => {
        if (year != null && year != undefined && truck_id != null && truck_id != undefined) {
            async function FetchQuarters() {

                const config = {
                    headers: {
                        "Content-Type": "application/json",
                        "Authorization": `Bearer ${token}`,
                    },
                };


                const trucks_url = `${domain}/quarter-taxes/taxes-report/${year}/${truck_id}`
                axios.get(trucks_url, config).then(async (res) => {
                    const result = await res.data

                    result.sort((a, b) => parseInt(a.number) - parseInt(b.number));

                    setQuarters(result);
                }).catch((error) => {
                    console.log(error)
                })
            }
            FetchQuarters();
        }
    }, [year, truck_id, token])


    console.log(quarters)

    return (user == null || quarters == null) ? <div></div> : (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NextNavbar />

            <main className={styles.main}>
                <div className={styles.trucks_info_div}>
                    {(trucks !== null) ? (
                        <div>
                            <div className={styles.quarter_taxes_filter_div}>

                            </div>
                            <Card className={styles.quarter_taxes_table_card}>
                                <Card.Header className={styles.quarter_taxes_table_card_header}>
                                    <Row className={styles.quarter_taxes_table_card_header_row}>
                                        <Col xs={3} sm={3} md={3} lg={3} className={styles.quarter_taxes_table_card_header_col}>
                                            <span className={styles.quarter_taxes_table_card_header_span}>
                                                QUARTER
                                            </span>
                                        </Col>

                                        <Col xs={2} sm={2} md={2} lg={2} className={styles.quarter_taxes_table_card_header_col}>
                                            <span className={styles.quarter_taxes_table_card_header_span}>
                                                MILES
                                            </span>
                                        </Col>

                                        <Col xs={2} sm={2} md={2} lg={2} className={styles.quarter_taxes_table_card_header_col}>
                                            <span className={styles.quarter_taxes_table_card_header_span}>
                                                GALLONS
                                            </span>
                                        </Col>

                                        <Col xs={2} sm={2} md={2} lg={2} className={styles.quarter_taxes_table_card_header_col}>
                                            <span className={styles.quarter_taxes_table_card_header_span}>
                                                MPG
                                            </span>
                                        </Col>

                                        <Col xs={2} sm={2} md={2} lg={2} className={styles.quarter_taxes_table_card_header_col}>
                                            <span className={styles.quarter_taxes_table_card_header_span}>
                                                IFTA TAXES
                                            </span>
                                        </Col>
                                    </Row>
                                </Card.Header>

                                <Card.Body className={styles.trucks_info_table_card_body}>

                                    {quarters == null ? <div></div> :
                                        <div>
                                            {quarters.map((quarter, index) => {
                                                return (
                                                    <Link key={index} href={`/credentials/manage-account/quarter-taxes-report/${year}/${truck_id}/${quarter.number}`}>

                                                        <Card className={styles.quarter_taxes_card}>
                                                            <Card.Body className={styles.trucks_info_card_body}>
                                                                <Row className={`${styles.quarter_taxes_table_card_row}`}>
                                                                    <Col xs={3} sm={3} md={3} lg={3} className={styles.quarter_taxes_table_card_col}>

                                                                        {(index == quarters.length - 1) ?
                                                                            <span className={styles.quarter_taxes_table_card_span_red}>
                                                                                QUARTER {quarter.number}
                                                                            </span> :
                                                                            <span className={styles.quarter_taxes_table_card_span}>
                                                                                QUARTER {quarter.number}
                                                                            </span>}
                                                                    </Col>

                                                                    <Col xs={2} sm={2} md={2} lg={2} className={styles.quarter_taxes_table_card_col}>
                                                                        {(index == quarters.length - 1) ?
                                                                            <span className={styles.quarter_taxes_table_card_span_red}>
                                                                                {quarter.toll_miles}
                                                                            </span> :
                                                                            <span className={styles.quarter_taxes_table_card_span}>
                                                                                {quarter.toll_miles}
                                                                            </span>}
                                                                    </Col>

                                                                    <Col xs={2} sm={2} md={2} lg={2} className={styles.quarter_taxes_table_card_col}>
                                                                        {(index == quarters.length - 1) ?
                                                                            <span className={styles.quarter_taxes_table_card_span_red}>
                                                                                {quarter.fuel_gallons}
                                                                            </span> :
                                                                            <span className={styles.quarter_taxes_table_card_span}>
                                                                                {quarter.fuel_gallons}
                                                                            </span>}
                                                                    </Col>

                                                                    <Col xs={2} sm={2} md={2} lg={2} className={styles.quarter_taxes_table_card_col}>
                                                                        {(index == quarters.length - 1) ?
                                                                            <span className={styles.quarter_taxes_table_card_span_red}>
                                                                                {quarter.mpg}
                                                                            </span> :
                                                                            <span className={styles.quarter_taxes_table_card_span}>
                                                                                {quarter.mpg}
                                                                            </span>}
                                                                    </Col>

                                                                    <Col xs={2} sm={2} md={2} lg={2} className={styles.quarter_taxes_table_card_col}>
                                                                        {(index == quarters.length - 1) ?
                                                                            <span className={styles.quarter_taxes_table_card_span_red}>
                                                                                ${quarter.fuel_tax_owned}
                                                                            </span> :
                                                                            <span className={styles.quarter_taxes_table_card_span}>
                                                                                ${quarter.fuel_tax_owned}
                                                                            </span>}
                                                                    </Col>
                                                                </Row>
                                                            </Card.Body>
                                                        </Card>
                                                    </Link>

                                                )
                                            })}
                                        </div>
                                    }

                                </Card.Body>
                            </Card>
                        </div>
                    )
                        : <div></div>}


                </div>

            </main>
        </div>
    );
}


QuarterTaxes.getInitialProps = async ({ query }) => {
    const { year, truck_id } = query;

    return { year, truck_id };
};