import Head from 'next/head'
import Image from 'next/image'
import CreateAccountTruck from '../../../components/CreateAccountTruck'
import NextNavbar from '../../../components/Navbar'
import styles from '../../../styles/Home.module.css'


export default function CreateTruckFunction() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" costent="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NextNavbar />

      <main className={styles.main}>
        <CreateAccountTruck />
      </main>
    </div>
  )
}