import Head from 'next/head'
import Image from 'next/image'
import CreateDriver from '../../../components/CreateDriver'
import styles from '../../../styles/Home.module.css'


export default function CreateDriverFunction() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" costent="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CreateDriver />
      </main>
    </div>
  )
}